apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-service
spec:
  template:
    spec:
      containers:
        - name: exchange-service
          volumeMounts:
            - name: postgres-credentials-volume
              mountPath: /workspace/secrets/postgres
            - name: rabbitmq-credentials-volume
              mountPath: /workspace/secrets/rabbitmq
            - name: keycloak-issuer-resourceserver-secret-volume
              mountPath: /workspace/secrets/keycloak
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: bookshop-postgres-exchange-credentials
        - name: rabbitmq-credentials-volume
          secret:
            secretName: bookshop-rabbitmq-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret