apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-service
spec:
  template:
    spec:
      containers:
        - name: exchange-service
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod