apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-service
spec:
  template:
    spec:
      containers:
        - name: exchange-service
          resources:
            requests:
              memory: 756Mi
              cpu: "0.1"
            limits:
              memory: 756Mi
              cpu: "2"
