apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/haihuynh2002/bookshop-catalog-service/k8s?ref=main


configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/haihuynh2002/bookshop-catalog-service
  newTag: latest

replicas:
- count: 1
  name: catalog-service

patches:
- path: patch-env.yml
