apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  template:
    spec:
      containers:
        - name: notification-service
          volumeMounts:
            - name: postgres-credentials-volume
              mountPath: /workspace/secrets/postgres
            - name: keycloak-issuer-resourceserver-secret-volume
              mountPath: /workspace/secrets/keycloak
            - name: rabbitmq-credentials-volume
              mountPath: /workspace/secrets/rabbitmq
            - name: bookshop-notification-brevo-volume
              mountPath: /workspace/secrets/brevo
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: bookshop-postgres-notification-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret
        - name: rabbitmq-credentials-volume
          secret:
            secretName: bookshop-rabbitmq-credentials
        - name: bookshop-notification-brevo-volume
          secret:
            secretName: bookshop-notification-brevo
