apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
spec:
  template:
    spec:
      containers:
        - name: file-service
          volumeMounts:
            - name: postgres-credentials-volume
              mountPath: /workspace/secrets/postgres
            - name: keycloak-issuer-resourceserver-secret-volume
              mountPath: /workspace/secrets/keycloak
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: bookshop-postgres-file-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret