apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/haihuynh2002/bookshop-order-service/k8s?ref=main

patches:
  - path: patch-env.yml
  - path: patch-resources.yml
  - path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: bookshop-order-service
  newName: ghcr.io/haihuynh2002/bookshop-order-service
  newTag: latest

replicas:
- count: 1
  name: order-service

