version: "3.8"
services:

  # Backing Services

  bookshop-postgres:
    image: "postgres:14.12"
    container_name: "bookshop-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  bookshop-redis:
    image: "redis:7.2"
    container_name: "bookshop-redis"
    ports:
      - 6379:6379

  bookshop-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: bookshop-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  
  bookshop-keycloak:
    image: quay.io/keycloak/keycloak:23.0.5
    container_name: "bookshop-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080