apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/haihuynh2002/edge-service/k8s?ref=main


configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/haihuynh2002/edge-service
  newTag: latest

replicas:
- count: 1
  name: edge-service
patches:
- path: patch-env.yml
- path: patch-ingress.yml
- path: patch-resources.yml
- path: patch-volumes.yml
