fullnameOverride: bookshop-keycloak
commonAnnotations:
  app: bookshop-keycloak
image:
  registry: docker.io
  repository: bitnamilegacy/keycloak
  tag: 23.0.5
keycloakConfigCli:
  image:
    registry: docker.io
    repository: bitnamilegacy/keycloak-config-cli
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
  primary:
    initdb:
      image:
        registry: docker.io
        repository: bitnamilegacy/postgresql
extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "--import-realm"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "false"
  - name: KC_HOSTNAME_STRICT
    value: "false"
extraVolumeMounts:
  - name: config-volume
    mountPath: "/opt/bitnami/keycloak/data/import"
    readOnly: true
extraVolumes:
  - name: config-volume
    configMap:
      name: keycloak-config
startupProbe:
  enabled: true
resources:
  requests:
    cpu: 0.2
    memory: 756Mi
  limits:
    cpu: 2
    memory: 756Mi
service:
  type: LoadBalancer
  port: 80

