apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/haihuynh2002/bookshop-ui/k8s?ref=main

patches:
  - path: patch-env.yml
  - path: patch-resources.yml

images:
- name: bookshop-ui
  newName: ghcr.io/haihuynh2002/bookshop-ui
  newTag: latest

replicas:
- count: 1
  name: bookshop-ui

