apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-ui
spec:
  template:
    spec:
      containers:
        - name: bookshop-ui
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod